# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install debootstrap
        run: sudo apt-get install -y debootstrap

      - uses: actions/cache@v4
        id: debootstrap-cache
        with:
          path: /srv/chroot/debian-bookworm
          key: ${{ runner.os }}-debootstrap-bookworm-cache

      - name: Install bookworm using debootstrap
        if: steps.debootstrap-cache.outputs.cache-hit != 'true'
        run: |
          sudo debootstrap bookworm /srv/chroot/debian-bookworm http://deb.debian.org/debian

      - name: Install bookworm using debootstrap
        if: steps.debootstrap-cache.outputs.cache-hit != 'true'
        run: |
          sudo chroot /srv/chroot/debian-bookworm apt-get update -y
          sudo chroot /srv/chroot/debian-bookworm apt-get dist-upgrade -y
